### ISSUE TITLE
Invalid type definition

### ISSUE THREAD

**Issue by windware** [adaltas/node-pad#10]
When I import it using the following format in TypeScript using this syntax,

> import * as pad from 'pad'

it shows,

> TS2497: Module '"node_modules/@ types/pad/index"' resolves to a non-module entity and cannot be imported using this construct.

**Comment by wdavidw** [comment]
I am no typescript expert, `pad = require('pad')` will just works.

**Comment by windware** [comment]
Made a PR in DT.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23339

**Comment by wdavidw** [comment]
What about packaging the TS definition file along this package ?

**Comment by jloveridge** [comment]
Publishing the types along with the package would be awesome. Then people wouldn't need to install the type data from definitely typed. To be done properly all you would need to do is include the definition file and then reference it in the `package.json`.

Download the current definition from: https://raw.githubusercontent.com/windware/DefinitelyTyped/87e566c278cf8d283d2c3e2da204b33b8d8c7f7c/types/pad/index.d.ts

Add it to the project somewhere that is published to NPM and then in `package.json` add the following (assuming that the definition file is saved to `lib/index.d.ts`):

```
"types": "lib/index.d.ts"
```

**Comment by wdavidw** [comment]
Thank you for your suggestion. If you are familiar with TypeScript, I'm looking for a clean way to test those typescript definition files in my projects. I'm thinking about declaring typescript as a dev dependency and having one test written in TypeScript and run by mocha to test the definition file. Would be happy to get some help in that regard.
