### ISSUE TITLE
Doesn't Work in IE 11 Due To Assignment Issue

### ISSUE THREAD

**Issue by piperRyan** [adaltas/node-pad#12]
Using the es5 version of this project, but IE 11 spits back the following error message: 

`Invalid left-hand side in assignment`

The stack trace points to this [line](https://github.com/adaltas/node-pad/blob/master/lib/es5/index.js#L13) as the culprit. 

Is there anyway to make this work with IE 11?

**Comment by wdavidw** [comment]
Sorry, I just release a new patch version which shall fix it.
