### ISSUE TITLE
Padding determined by string length?

### ISSUE THREAD

**Issue by realph** [adaltas/node-pad#13]
I'm having an issue where I see a different amount of padding depending on the string length.

    commands[type].commands.forEach(cmd => {
      console.log(pad(10, cmd.name), cmd.type, cmd.description);
    });

![image](https://user-images.githubusercontent.com/2334951/51527919-782baa80-1e2d-11e9-9766-cb1ac0ea37c2.png)

I would like both lines to start with the same amount of padding so they're aligned. Like so:

```
    add cmd Adds a game to your library
    help cmd Displays complete help for [cmd]
```

Is there a way to fix the amount of padding? I've tried the `fixed_width` option with no luck.

Any help is appreciated. Thanks in advance!

**Comment by sergkudinov** [comment]
Hi @realph 
In that case you should calculate the amount of padding manually. If the strings have different sizes you should first calculate their length.

Try this:
```
commands[type].commands.forEach(cmd => {
  console.log(pad(4 + cmd.name.length, cmd.name), cmd.type, cmd.description);
});
```

**Comment by wdavidw** [comment]
Thanks @sergkudinov, closing.
