### ISSUE TITLE
Unmet peer dependency: rollup@>=0.56.0

### ISSUE THREAD

**Issue by VivekMChawla** [adaltas/node-pad#15]
I'm using pad in a node.js package of mine and my users are getting an "unmet peer dependency" warning when they install my package. (see below)

![image](https://user-images.githubusercontent.com/1161504/57582673-7b01e800-747c-11e9-8e5c-67522b75eeca.png)

Should rollup be added to your package's list of dependencies to address this?

**Comment by wdavidw** [comment]
The `rollup` dependency is only used in development and declared in the "devDependencies" field. Since the generation of multiple bundles with rollup is a new addition, I've made a simple test and it seems to work:

```bash
mkdir toto
cd toto
npm init
npm add pad
echo 'const pad = require("pad");\nconsole.log(pad("hello", 10, "_"))' > test.js
node test.js
```

**Comment by joepie91** [comment]
Is there a reason why there a bunch of Rollup plugins in the `dependencies`, rather than in the `devDependencies`?

```js
  "dependencies": {
    "rollup-plugin-commonjs": "^9.3.4",
    "rollup-plugin-node-resolve": "^4.2.3",
```

This appears to be what's responsible for dragging in a large pile of (unnecessary?) dependencies and causing the 'unmet peer dependency' warning being discussed here.

**Comment by wdavidw** [comment]
Thank you @joepie91 , this is a mistake which I didn't catched when looking at @VivekMChawla issue. I have published a new release 3.2.0 which fix the issue.

**Comment by joepie91** [comment]
Thanks for the quick fix :)

**Comment by VivekMChawla** [comment]
Thanks, @joepie91 for articulating the correct issue.  And thank you, @wdavidw, for the quick fix!
