### ISSUE TITLE
breaks when padding strings with weird characters

### ISSUE THREAD

**Issue by slang800** [adaltas/node-pad#8]
Unicode has characters that take up 2/+ spaces, zero spaces, half spaces, and even some that take up multiple lines like 𒐫. For example, `"操作类型".length == 4`, but it takes up 8 columns when rendered.

This breaks the pad function when you're using it for visual alignment, which I think is a pretty common use-case. You can mostly fix this by getting the visual length of the string with [wcwidth](https://github.com/timoxley/wcwidth) and using that for all calculations in the function... wcwidth isn't perfect, but it seems to fix most of the issues that affect Chinese characters.

Also, I'm not sure how you'd work around the usage of multi-column wide pad characters.

**Comment by wdavidw** [comment]
OK, interesting issue, it took me a second look at your description to really understand its topic. I didn't know some character, like in chinese, take more than one column to display. Here are the pros and cons:

* Using wcwidth for all length calculation will introduce a new and first dependency to this lib
* It will slow performances
* It could be made optional, concerned users like chineses, would have to install the dependency and pass an option, perfermances will be preserved for others but it will much less convenient for the concerned crowd

What's your opinion on this ?

**Comment by slang800** [comment]
I don't think there's a good way to solve this because character width in Unicode introduces some really ugly problems. However, I do think pad should "just work" to the greatest degree possible, especially with characters that users are likely to run into. Adding a way to pass in a custom length function just means that users need to learn about this Unicode issue on their own and solve the problem themselves, rather than having it work automatically. I could see how disabling wcwidth usage could be desirable, but for the average user, I think they want to pad strings to the width that the string will be displayed at.

I found out about this issue after getting bug reports from users of [tidy-markdown](https://github.com/slang800/tidy-markdown) who were trying to format tables that had Chinese characters. That project uses pad to handle table alignment, so removed it for now: https://github.com/slang800/tidy-markdown/commit/afba38be39d814ef5df1a16bbefd7b3f078960cf.

Normally, I don't work with Chinese characters, so I would have never noticed this on my own and only fixed it because someone who does write in Chinese started using my software. So, I don't think that only Chinese users will have to worry about this - my software could end up being used by anyone.

Side note: implementations elsewhere,  like `rjust` / `ljust` in Python also [don't handle Chinese chars correctly](https://stackoverflow.com/questions/23320148/how-to-control-output-format-when-chinese-characters-and-ascii-mixed).

**Comment by wdavidw** [comment]
I agree with your reflexion. Fixed with #639d57a17339a1727cc33e8a564c009d72023ea4. I also am not concerned with multi column chars so let's hope this commit fix it right.
