### ISSUE TITLE
Latest release containing breaking changes

### ISSUE THREAD

**Issue by jbernalvallejo** [adaltas/node-pad#9]
Hi, we ran `npm install` today for a package which consumes pad. It got the latest version published yesterday. 

It now breaks with the following error:

```
module.exports = function(text, length, options = {}) {
                                                ^
SyntaxError: Unexpected token =
```

Was this intentional? That is not JS code and it must be failing unless I am missing something... If so, should not that release be a mayor one?

**Comment by wdavidw** [comment]
Thank you for reporting this issue. I've just pushed a new version on NPM. This release did not introduced intentionnaly any change of API, only new features, this is why it was tagged as a minor. I didn't realised the latest version of CoffeeScript was generating default variable.

On which version are you, i run a quick test with node 6 and it was ok ?

**Comment by autowp** [comment]
Probles is uglifyjs bundled with webpack 3.6.0
```
ERROR in 7448d9be54984e73afdd.js from UglifyJs
Unexpected token operator «=», expected punc «,» [7448d9be54984e73afdd.js:156,107576]
```

**Comment by wdavidw** [comment]
Can't you put babel in front of it ?

**Comment by jbernalvallejo** [comment]
I was using "^1.0.0" and hence I got 1.2.0 which included the `options = {}`. Which is the version I shall use then?

Thanks for your quick reply.

**Comment by wdavidw** [comment]
1.2.1 will fix it

**Comment by autowp** [comment]
Putting babel in front follows huge performance issue. Typical babel usage is exclude `node_modules` 

```
module: {
  rules: [
    {
      test: /\.js$/,
      exclude: /(node_modules|bower_components)/,
      use: {
        loader: 'babel-loader',
        options: {
          presets: ['env']
        }
      }
    }
  ]
}
```

**Comment by wdavidw** [comment]
I just publised a new version v2.0.1 which use coffee2 while preserving js compatibility, I should have think about this solution for 1.2.1 but too late.
